school-journal:
  base-url: http://school-journal-app:8080
  endpoints:
    grades: /grades
    subjects: /subjects
    coreCrash: /core/crash


subjectcache:
  printdelay: 5000
  cachestatstring: Subject cache statistics
  statistics:
    rate: 30000